### ISSUE TITLE
Update my organization member role

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/materiales-front-end-H#2]
Hi, @migueldelmazo, I know you must be totally buried with the new promo's preparations, but I'm worried about being an administrator of the ADALAB organization. It would be great if you change my current role to "member" or "external collaborator", either of them is ok.

I tried to do it myself but GitHub tells me that someone else has to do it.

![Please](https://media.giphy.com/media/mrZcf6eYn3bz2/giphy-downsized.gif)

**Comment by migueldelmazo** [comment]
Hola señoría, te he puesto como colaborador externo. Si quieres algún cambio más dímelo sin problema!!

**Comment by oneeyedman** [comment]
Gracias, me quedo más tranquilo. Así no puedo borrar la organización entera por error, ni echaros a todos y quedármela, también por error :)

![Yay](https://media.giphy.com/media/Mp4hQy51LjY6A/giphy-downsized.gif)
